### ISSUE TITLE
Add optional flag to ignore missing tickets

### ISSUE THREAD

**Issue by diogofalken** [Justin-JHG/jira-release-actions#603]
**Description:**

Currently, our pipelines encounters a failure when attempting to assign non-existent Jira tickets to a release version. This issue often arises when placeholder tickets (e.g., JRA-000) are used for minor changes that don't warrant a formal Jira ticket.

When the action runs, the presence of any non-existent ticket in Jira causes the entire job to fail. This can lead to releases being created but not properly closed, as the associated (but missing) ticket prevents completion.

**Proposed Solution:**

Introduce a new optional input, `ignore_missing_tickets` (boolean, default: `false`). When set to `true`, this input will allow the action to continue processing even if some tickets do not exist in Jira, preventing job failures.

**Example Usage:**
```yaml
    - name: Create Jira Release
      uses: justin-jhg/jira-release-actions@v2
      with:
        jira_base_url: ${{ secrets.JIRA_BASE_URL }}
        jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
        jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
        jira_project: CI
        tickets: CI-123,JRA-000,CI-456
        release: true
        archive: false
        ignore_missing_tickets: true
```

**Comment by Justin-JHG** [comment]
```
    - name: Create Jira Release
      continue-on-error: true
      uses: justin-jhg/jira-release-actions@v2
      with:
        jira_base_url: ${{ secrets.JIRA_BASE_URL }}
        jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
        jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
        jira_project: CI
        tickets: CI-123,JRA-000,CI-456
        release: true
        archive: false 
```
hi @diogofalken 
thank you for using this action. 
what I normally do is add the following so error on this step will be ignored and I believe the release would still be created even no ticket number provided.

`continue-on-error: true`

please have a look see whether it is ok and let me know thanks.
